### ISSUE TITLE
Should allow sorting

### ISSUE THREAD

**Issue by wernight** [google/google-authenticator-android#1]
The Google Auth Android client works well for a few entries. People like me have about 20 entries, not sorted (well sorted by when you've added them which is meaningless). You should be able to:

Sort them (manually, by issuer, or by provider, at least one of those)
Possibly group them together in one level tree

**Comment by mash55** [comment]
Second that, search capabilities would be nice too.

**Comment by wernight** [comment]
@vovtz Yes that's also my desire. Manually sorting is probably the most important.

**Comment by AndrewKvalheim** [comment]
For what it's worth, I've had success with manually reordering entries in the SQLite database.

**Comment by capi** [comment]
I think a very basic way would be quite easy to achieve (add a `position` column to the database) and load it sorted by this column. The harder part is getting a UI. Using context menu action like "move up/down" or "to top" the pure functionality could be added. Things like drag&drop sorting are the more harder UI part.

**Comment by vovtz** [comment]
@AndrewKvalheim So I have to ‘root’ my phone to be able re-order the entries? ;p

**Comment by vovtz** [comment]
@capi Wish I had time to play with the drag and drop support myself: [Drag and Drop | Android Developers] (http://developer.android.com/guide/topics/ui/drag-drop.html) …

**Comment by AndrewKvalheim** [comment]
@vovtz Yes, hence the existence of this issue.

**Comment by capi** [comment]
@vovtz @AndrewKvalheim `root` is also a working solution for #23. But `root` is also the root of all evil for the security aspects of the application :)

PS: I know you've both been only kidding.

**Comment by abominab** [comment]
Would love this as well

**Comment by ajolo2ky** [comment]
+1

**Comment by ElectricSwan** [comment]
+1 for comment by @vovtz  "I’d prefer to be able to freely re-order the accounts". The order that my accounts were created does not reflect the frequency with which I use each account. My currently most used entries are the first, and the third-last!

**Comment by ThomasHabets** [comment]
Just FYI: The opensource project for GA is unstaffed, so don't expect this to "just happen". Patches will be accepted though.

**Comment by bradmurray** [comment]
The solution is to use [Authy](https://www.authy.com/app/)

**Comment by wernight** [comment]
@bradmurray Everyone knows how to find other OTP generators for Android on the Play Store and there are IMO better ones but I'd not link to any especially not one that is open source. The goal isn't to advertise but to work on improving this app.

**Comment by bradmurray** [comment]
But there are many people who don't have the skills to update the app that may not know about alternatives since most sites that support Google 2FA don't mention them. This project is basically dead so users hoping for an update will be waiting for a long time for something that may never come and already exists elsewhere.

**Comment by wernight** [comment]
The project being dead is more a speculation as it lives internally of
Google.

As for the rest it's a issue tracker and not a forum. Please avoid

**Comment by ocdtrekkie** [comment]
@wernight "This project" is open source. What is happening internally at Google (the Play Store version of this app) is not open source. One is 'free software', one is not.

**Comment by wernight** [comment]
I'd open a new ticket to suggest marking this project as dead/deprecated and/or for including pointers to other similar OTP applications in the README.

@ocdtrekkie Yes you're right (I get what you're meaning even though both are free one isn't open source). My point is more that there isn't a firm plan for this repository as far as I'm aware.

**Comment by capi** [comment]
Pull-requests are accepted by @ThomasHabets very fast. It's just that no-one is providing any at the moment.

**Comment by dlr1967** [comment]
+1

**Comment by strigona-worksight** [comment]
@dlr1967 in the latest Authenticator release, you can sort entries by long-pressing an entry then dragging up or down.

**Comment by rhcarvalho** [comment]
Took me some effort to figure out how to drag & drop, but I confirm it works in GA 5.00 (Android Oreo).

First you have to long-press one of the entries: it will be highlighted and there will be a notification "Verification code copied to clipboard". After that, it is possible to drag and drop the selected entry and reorder the list.

Not the easiest and most intuitive UI, but it works. I guess this issue could be finally closed?

**Comment by ThomasHabets** [comment]
Most people care about the non-opensource GA, so yeah I'll just close this.

Thanks.
