### ISSUE TITLE
Current Google Authenticator Version does not work on Android 2.3.7

### ISSUE THREAD

**Issue by martijintro** [google/google-authenticator-android#105]
Buy they write it works on Android 2.3.3 ?!?!

Message: 

"Die Anwendung Authenticator (Prozess com.google.android.authenticator2) wurde unerwartet beendet. Versuchen Sie es erneut."

Thx for feedback!!

**Comment by ThomasHabets** [comment]
Duplicate of https://github.com/google/google-authenticator-android/issues/106

ಠ_ಠ
