### ISSUE TITLE
Query the function of the specified account

### ISSUE THREAD

**Issue by ninetzt** [google/google-authenticator-android#107]
When the account is more and more, it takes time and effort to check the account.

**Comment by arjunamrith** [comment]
Is this a search feature? Because having a search feature would simplify the usage a lot as I have many accounts added to my authenticator and its a pain to find some accounts on time. 

I also think some sort of tagging and maybe a grouping of accounts would help make the app more usable

**Comment by ThomasHabets** [comment]
I'm closing this one as the original comment is not readable. Feel free to open a new bug with your suggestion, @arjunamrith.

But, standard disclaimer:

FYI: The version in Google Play Store / Apple App store is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the app stores. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.

**Comment by ThomasHabets** [comment]
Also see #78
