### ISSUE TITLE
Invalid Codes for 3rd Parties

### ISSUE THREAD

**Issue by bridgetsarah** [google/google-authenticator-android#110]
Hello,

Normally I have no issues with the google authenticator as a user but yesterday on my android phone I tried logging into one of my accounts with the following providers that support the Google authenticator. 

 

- Digital Ocean - Providing with invalid codes, unable to login (Yesterday)
- Stripe (Today) - Unable to login completely, had to reset account. 

Can anyone please confirm if this might be a bug as this will be a certainly an issue as by law I am required to use this for my business.

**Comment by ThomasHabets** [comment]
No response.
