### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [google/google-authenticator-android#114]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

**Comment by tentacleuno** [comment]
Nice sentiment, but this is wishful thinking. When even the main developer of this repo admits the open-source variant ["doesn't get much love"](https://github.com/google/google-authenticator-android/pull/112#issuecomment-596486569), it's plain to see that Google have little to no interest in maintaining this project in the appropriate manner. I realise we've come to expect a modicum of decency from open-source 'pioneers', but I won't be holding my breath.

Maybe [Aegis](https://f-droid.org/en/packages/com.beemdevelopment.aegis/) fits the bill a little better. I'm told it has better security.

**Comment by pplupo** [comment]
Indeed. I just used aegis to login and com comment here. This app looks abandoned, really.

**Comment by rugk** [comment]
https://github.com/google/google-authenticator-android/issues/129

**Comment by ThomasHabets** [comment]
> a modicum of decency from open-source 'pioneers'

That's a bit harsh. I'm not involved in headcount decisions, but allocating resources to something for all time out of altruism goes way beyond "modicum of decency".

The current version of Google Authenticator on Play Store is not this source code. But I'll check with the team. It may be that archiving this project would be best, unless they want to keep it alive.

Seems that most I do nowadays is to tell users of crime coins that there's nothing I can do if they got locked out and if they want their crime coin exchanges to let them back in then they shouldn't have been involved in crime in the first place, and it was never a real bank.

**Comment by tentacleuno** [comment]
> That's a bit harsh. I'm not involved in headcount decisions, but allocating resources to something for all time out of altruism goes way beyond "modicum of decency".

It wasn't aimed at you specifically. I was referencing the company who maintains an ["iron-grip"](https://arstechnica.com/gadgets/2018/07/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/) (good read) over anything they misleadingly publish as 'open-source'. **14 years on**. The false narrative is belittling and is an attempt to pander to the open-source crowd who, in actual fact, are of no consequence to the middle aged white men running this country into the ground. 

All in an honest day's work, eh.

> It may be that archiving this project would be best, unless they want to keep it alive.
 
Yeah. The new Play Store app has been majorly updated with the new proprietary Google material design theme, which hasn't been included in any of their open-source offerings so far. I can't see the open-source variant receiving that update. The basic functionality is there, but this app will most likely end up on the scrap heap like every other 'open-source' app Google have given us.

@ThomasHabets Maybe I'll see you next time when we get a new 'open-source' app, eh? 👋🏾

**Comment by ThomasHabets** [comment]
I'll make sure to let [the white man](https://en.wikipedia.org/wiki/Sundar_Pichai) know.

Personally I don't think that giving something for free comes with obligations on the giver (aside from things like giving a knife to a toddler). People abandon open source projects all the time.

But anyway, this is not the forum for a discussion.

I'm closing this bug, because it doesn't look like I'm more able to put this on F-Droid than you are. And while I'm not in a position to grant any permissions or legal stuff, so don't infer any permission if any is needed, why don't you?
