### ISSUE TITLE
google authenticator 2fa key value illegal character

### ISSUE THREAD

**Issue by wonwayrt** [google/google-authenticator-android#125]
My key code has a `#9` this is now an illegal character. How can I use my key code when it worked before when I set up account and `#9` was acceptable. Unable to scan or enter key code in authenticators.

**Comment by ThomasHabets** [comment]
I don't understand what you're doing, what happens, and what you expect to happen.

**Comment by wonwayrt** [comment]
I am trying to scan barcode Google says error. I enter Key code #9 is error. My key code has #9 that is why scan is error. I checked another wallet that has a #9 and it will not scan. These wallets were scanned 2 years ago and they worked now they do not work.

**Comment by ThomasHabets** [comment]
I don't know what a "key code" is, but could you not have that symbol in it?

I also don't know what the QR code is. It's being generated by some crimecoin site? Maybe they are generating invalid QR codes?

**Comment by wonwayrt** [comment]
Key code is generated with the scan. Google authenticator asks for Scan or Key code.
