### ISSUE TITLE
Authenticator crashes in attempt to read a barcode

### ISSUE THREAD

**Issue by mariomelofilho** [google/google-authenticator-android#14]
How to reproduce:
1- Open Autenticator
2- Choose "Start Configuration"
3- Choose  "Read Barcode"

Application crashes before camera opens.

Android Version: 5.0
Celphone: Motorola Moto X second generation.

**Comment by ThomasHabets** [comment]
What version of Google Authenticator?

**Comment by mariomelofilho** [comment]
Hi,
 2.49

**Comment by ThomasHabets** [comment]
So this is the version in the app store? That forked off of this code long ago, so nothing that can be done here, really.

**Comment by mariomelofilho** [comment]
yes, this is app store version :(
