### ISSUE TITLE
Authenticator crashes on "start setup"

### ISSUE THREAD

**Issue by m8ram** [google/google-authenticator-android#15]
**What steps will reproduce the problem?**
1. Open Authentication
2. Try to put Begin Setup button
3. Immediately unfortunately, authentication has stopped

**What is the expected output? What do you see instead?**
Immediately unfortunately, authentication has stopped

**What version of the product are you using? On what operating system?**
Package version 49
package version name: 2.49
On Android
device: LG G3

**Please provide any additional information below.**

This issue was originally reported on google code (https://code.google.com/p/google-authenticator/issues/detail?id=353) and then reopened on github (https://github.com/google/google-authenticator/issues/346) but both records are closed.
However the issue still occurs.

**Workaround**
Originally posted on google code and reproduced at http://lifeisabug.com/google-authenticator-crashes-account-setup-workaround/

1. Open Authenticator but do NOT press the “Begin setup” button.
2. Instead, select “setup account” from the option menu.
3. Then from another device, go to https://accounts.google.com/b/0/SmsAuthSettings, select “Move to a different phone” and scan the QR code.

**Comment by ThomasHabets** [comment]
Version 2.49 is a give-away that this is not the opensource version you're running. This project is for the opensource version only.
