### ISSUE TITLE
Support to store secret keys on YubiKey

### ISSUE THREAD

**Issue by jtyr** [google/google-authenticator-android#21]
It would be great if the Google Authenticator would have support to store the secret keys on an external secure storage like YubiKey. The current implementation is not very secure as the secure keys are stored as a plain text in the SQLite DB. If the device is compromised, the attacker can potentially compromise the account secured by the secret key.

The implementation should be similar to [Yubico Authenticator](https://play.google.com/store/apps/details?id=com.yubico.yubioath). That would allow to secure applications which do not support YubiKey directly.

**Comment by ThomasHabets** [comment]
Both Google Authenticator and this Yubico Authenticator use the standardized TOTP and HOTP algorithms. You should be able to use Yubico Authenticator with anything that you use Google Authenticator for.

For example, to use with your Google account you should be able to use the QR code you normally program Google Authenticator with, and instead program a Yubikey with it.

At least that's how I understand Yubico Authenticator works, from what you linked to.

**Comment by jtyr** [comment]
I'm currently using YA and it works just fine although it's a bit clunky ;o) I just thought it would be nice if GA would support YubiKey to provide higher level of security.

**Comment by akerl** [comment]
@jtyr what is the benefit of using Google Authenticator with key storage in the Yubikey vs using YA directly?

**Comment by ThomasHabets** [comment]
Seems to me like it's out of scope of GA.

**Comment by jtyr** [comment]
@akerl The difference is that not all services are supporting direct authentication with YubiKey. This is where the GA is handy as you can use it for multiple accounts. So it is worth to protect the secret keys by storing them on the YubiKey instead of into the SQLite DB.

@ThomasHabets Since when is the security out of the scope of GA?

**Comment by ThomasHabets** [comment]
Correct me if I'm wrong, but what you're describing is, right now, entirely implemented by YA?

It's all HOTP & TOTP, so YA should work with everything that GA works with.

**Comment by jtyr** [comment]
Yes, you are right, all required is implemented by YA. I just thought that if the same would be implemented in GA, a lot of users (5M+ GA users vs. 10k+ YA users) would see the option and possibly start using more secure way of storing their secure keys.

**Comment by ThomasHabets** [comment]
Yes and no. It's complicated. This is the OpenSource Google Authenticator, and the one on the Play store has diverged a long time ago. It's very unlikely that this opensource version will end up on the Play store.

The open source version is also unstaffed. Yes, a nice implementation of Yubikey support is probably something I'd accept as a pull request, if it doesn't add dependencies and complications. But I'm not expecting this to happen.

Adding to that, there's the fact that U2F is more convenient and more secure (e.g. for HOTP you can pre-generate a few keys and use them later, and for TOTP you can set the phone clock to be in the future, and get an OTP that's valid later on). With U2F the key was provably present at the time of auth, which is not the case for HOTP and TOTP. POTP (which I hadn't heard of before it was mentioned [here](https://github.com/google/google-authenticator/issues/496) should make this better).

The standard for U2F over NFC is, last I checked, not final, so the better solution may be to use that (or POTP) and this intermediate step of protecting the keys with yubikeys may not be worth it. If you want it now, it's in YA.

U2F-compatible Yubikeys are also much cheaper than NFC-capable ones. $50 vs $18. Doesn't help if AWS doesn't (yet) have U2F support, but for Google accounts they work.

**Comment by jtyr** [comment]
Thanks, Thomas. I really appreciate the time you spent on explaining me all the details.
