### ISSUE TITLE
Fails in Android 5.0

### ISSUE THREAD

**Issue by simonbcn** [google/google-authenticator-android#22]
There are several [comments in Google Play](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en) about the crashes in Android Lollipop (specially in LG G3 mobile).
In my device (LG G3) with Android 5.0 crashes when I press "_Start configuration_" and when I select (in menu) "_Configuration_" > "_Hour correction in codes_".

**Comment by ThomasHabets** [comment]
The version in Google Play is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the play store.

Please reopen if this also applies to this opensource version.

**Comment by simonbcn** [comment]
ok, and where I can report the error for Android app of Google Play?

**Comment by ThomasHabets** [comment]
You can file feedback from within the app, I believe. Make it crash, then restart the app and file the feedback.

Also, if the app crashes it should give you an option to file feedback then and there. While it may feel like these kinds of reports go into a void, they don't.
