### ISSUE TITLE
Bug with time causes all tokens to be incorrect

### ISSUE THREAD

**Issue by Tozzje** [google/google-authenticator-android#25]
I noticed a few days/weeks ago that all tokens generated by the Google Authenticator app were deemed invalid. None of the accounts/websites accepted the generated keys. Nothing obviously happened on my phone. I didn't reset it, didn't replace it with a new handheld or anything else.

After some fiddling around and changing the date/time settings and setting the checkbox on "Use 24-hour notation" in the Android settings the issue was resolved.

Apparantly the Authenticator app does not work properly anymore when the 24-hour vs am/pm notation is changed.

It is unclear to me why the 24-hour notation was changed into am/pm in the first place, as I prefer 24-hour notation. However, this could have been my kid fiddling around on my phone or I could have done it by accident.  But nevertheless, the Authenticator app shouldn't stop working after changing time display settings.

I believe this is a bug.

**Comment by yakushevi** [comment]
Having a similar issue with LG G3 Android 5.0

All tokens generated by the authenticator app for three different accounts are invalid.
When trying to use the time correction feature - the app crashes.

**Comment by oalders** [comment]
Having a similar issue on DASH JR K, Android 4.4.2  Switching the time to 24 hour notation didn't help.  Ended up using FreeOTP, which "just worked".

**Comment by ThomasHabets** [comment]
@oalders if it doesn't work at all, no matter what time notation you use, then your issue is most likely #4, unless you built Authenticator yourself from this repo.

**Comment by oalders** [comment]
@ThomasHabets thanks for this.  I'm using version 2.49 which I downloaded from the Play Store yesterday.  Do you know if the fix for #4 was shipped with that version?

**Comment by ThomasHabets** [comment]
@oalders I think it's not. But it will be in the next release.

**Comment by ThomasHabets** [comment]
Fix from #4 is in the app store version now. Reopen if you can reproduce this with the open source version.
