### ISSUE TITLE
All accounts lost after installation on new device

### ISSUE THREAD

**Issue by barbalex** [google/google-authenticator-android#26]
My mobile phone died yesterday (android 5.1.1 Nexus 5).

Today I set up the replacement (android 5.1.1. Nexus 6). But after installing google-authentticator only the google account appears. None of the others do. I am pretty messed up trying to access my diverse accounts now. Not to mention that the account list was very long and I can't even find a way to list up for which services google authenticator was set up.

Has something gone wrong? Or is this expected behaviour?

**Comment by ocdtrekkie** [comment]
Google Authenticator doesn't sync your tokens anywhere. You have to set these up manually on each device. Another option (which isn't recommended) is to keep a paper hardcopy of the QR code used to set up your Authenticator codes when you add them to the app, so you can add it to another device at a later time.

**Comment by barbalex** [comment]
o.k., thanks
security comes with little drawbacks ;-)

**Comment by skironDotNet** [comment]
Use KeePass with KeeOtp plugin to store OTP priv key and then you can easly scan back to phone using my version of a KeePassQRCodeView plugin https://github.com/skironDotNet/KeePassQRCodeView/releases/tag/v1.0.5
