### ISSUE TITLE
Key change dynamically

### ISSUE THREAD

**Issue by edersonsandre** [google/google-authenticator-android#27]
I wonder if it is possible to change the key generation of dynamic way?

Changing the getSecret () method it is possible to generate the token, but in validation in the application is not possible.

One observation is that I'm not using google but in a company's authentication system.

**Comment by ThomasHabets** [comment]
Key generation? I'm not quite following what you mean, could you clarify?

**Comment by ThomasHabets** [comment]
Closing due to clarification not provided.
