### ISSUE TITLE
Bug with calculation causes all tokens to be incorrect on some devices, for Google Authenticator 2.49

### ISSUE THREAD

**Issue by johnnytemp** [google/google-authenticator-android#28]
I encountered always wrong verification code on my phone, e.g. 396731, correct is 396709.

The correct code is found by using php's Google Authenticator's source code.  The wrong code is 22396709 mod 999999, instead of mod 1000000  (always reproducable).  The tested phone is Lenovo S930, android 4.4.2.

Not sure if the bug is related to the logic in this project. Thus reported here for reference.

Some corresponding parameter of the final code 396709
----
hmac output:  287f5c148333f125aa4507950eca8155bf25556e
final 32-bit integer before mod 1000000:  22396709

**Comment by ThomasHabets** [comment]
Sounds like it's the same as https://github.com/google/google-authenticator-android/pull/4 .

Status of that is that it's fixed in this open source version, and will be in the next closed source release. When that will be is out of my domain.
