### ISSUE TITLE
Crashes on time sync

### ISSUE THREAD

**Issue by helger** [google/google-authenticator-android#31]
Ever since I upgraded to Android 5.0 Authenticator codes no longer work and if do `Settings -> Time correction for codes -> Sync now` the app crashes.

**Comment by ThomasHabets** [comment]
The version in Google Play is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the play store. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.

Is this bug with the opensource version?

**Comment by helger** [comment]
Ok thanks. The bug is with the Play store version.
