### ISSUE TITLE
Cannot scan QR code with "QR & barcode scanner"

### ISSUE THREAD

**Issue by Wooty** [google/google-authenticator-android#42]
Android 6.0.1 / Samsung Galaxy 7 Edge

Installed authenticator from the store. Run authenticator, Tap "Begin setup", tap "Scan a barcode", back to the "Begin setup" page rather than the scanner opening to scan the QR code.

This seems to be in an infinite loop. I have used the authenticator succesfully on other android devices but not seen this issue before. Have re-installed a couple of times with no success and cannot find any help elsewhere for this issue.

Any ideas?

**Comment by ThomasHabets** [comment]
Do you have a barcode scanner installed?

**Comment by Wooty** [comment]
Thanks for the quick response.

Yes I do have - again, from the store "QR & barcode scanner". I believe it is the same one I have have installed on my working Sony Z3.

**Comment by Wooty** [comment]
Update: the scanner is https://play.google.com/store/apps/details?id=com.gamma.scan

**Comment by ThomasHabets** [comment]
I don't really know why this could be. Could you try installing https://play.google.com/store/apps/details?id=com.google.zxing.client.android and trying again?

**Comment by Wooty** [comment]
Hi Thomas,

Thanks for the information - installing the app you specified has resolved
the issue and I am now able to scan a QR code.

Do you need anything from me to try and resolve why the first scanner wasnt
recognised?

Once again, thanks for the assistance - glad to have my old friend back and
working again ;)

On 17 May 2016 at 09:01, Thomas Habets <notifications@github.com> wrote:

> I don't really know why this could be. Could you try installing
> https://play.google.com/store/apps/details?id=com.google.zxing.client.android
> and trying again?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-authenticator-android/issues/42#issuecomment-219646768>
>



-- 
There are 10 different types of people in the world. Those who understand
binary and those who do not.

**Comment by ThomasHabets** [comment]
Inserting canned answer:
---
FYI: The version in Google Play Store / Apple App store is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the app stores. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.
---

So the answer is that I think this should be enough information to work on the issue, but don't count on it being picked up.

**Comment by Wooty** [comment]
OK, thanks again for the quick assistance.

**Comment by 5dnick** [comment]
i factory reset my phone and this fixed NOTHING. i did however find an elegant solution 5 minutes later.  save the image of the QR code. open in photoshop or somesuch app and zoom in. hey presto, big qr that will scan. FUCKING A

**Comment by 5dnick** [comment]
this is also my first github post. HELLO ALL
