### ISSUE TITLE
Codes specifically not working with GitHub

### ISSUE THREAD

**Issue by ghost** [google/google-authenticator-android#43]
I noticed that my codes were not working with my Github account. Assuming it was a time sync issue, I tried to perform time correction and received the following error:

```There was a problem contacting Google's server. Please check your network settings and try again.```

Upon making a new account, I tried enabling 2fa via Google Authenticator again and the codes did not work.

**Comment by ThomasHabets** [comment]
Do codes on the same device work with Google accounts?

Have you tried deleting the GA and re-enrolling it?

**Comment by ThomasHabets** [comment]
Closing due to clarification not provided.
