### ISSUE TITLE
Provide source code for 2.49

### ISSUE THREAD

**Issue by capi** [google/google-authenticator-android#5]
The currently available version in the Play Store is `Google Authenticator 2.49`, while the source here reflects the already very old version 2.21.

It would be very nice by Google to provide source code for the latest release as well, which I would highly appreciate for such a sensitive security application like a secure token generator.

**Comment by ThomasHabets** [comment]
I have copied the message from https://github.com/google/google-authenticator/wiki/Overview into the wiki for this project.

Relevant part: "This open source project allows you to download the code that powered version 2.21 of the application. Subsequent versions contain Google-specific workflows that are not part of the project."

Don't shoot the messenger.

**Comment by capi** [comment]
How embarrassing, I searched for an announcement like this (and almost expected it), but I skipped over the most obvious location. Sorry.

**Comment by ThomasHabets** [comment]
The most obvious location (the wiki page for *this* project) is only populated now, it was only in the non-android github project until just now. So don't feel too bad. :-)

Also this may be relevant if this opensource version is not solving your problem:
http://en.wikipedia.org/wiki/Google_Authenticator#Open_Source_status_on_Android
