### ISSUE TITLE
Authenticator code issue when logging into github

### ISSUE THREAD

**Issue by codeepic** [google/google-authenticator-android#60]
I am trying to clone my company's github repo. After I 'git clone' the repo Github login box comes up.  I put my username and password and now I am asked for two-factor authentication. I get the code from the Authenticator app on my Samsung S7 and put it in just to see 'Logon failed' in command line. I already synced the time in the app, it was right in the first place.

I am locked out from accessing my own work and this happened to me for 2nd time. The last time it I was able to get the authentication code that works by using my old mobile.

Edit:
It worked for me now as well by using my old mobile which means that the authenticator app on my new mobile generates wrong codes. How is it possible? Why the codes generated by my newer mobile are completely different (and wrong) than the codes generated by the old mobile (I was comparing the two apps for a few minutes.)

**Comment by ThomasHabets** [comment]
Read the comments on https://github.com/google/google-authenticator-android/issues/56. Sounds like a github issue.
