### ISSUE TITLE
App crashes on startup on Android 2.3.6 (Gingerbread)

### ISSUE THREAD

**Issue by JackDinn** [google/google-authenticator-android#70]
The play store indicated that the update for google authenticator that my android phone was asking to do was compatible with my old phone, so I updated. I was concerned, so I checked and double-checked. Now it just crashes.

The application Authenticator (process com.google.android.apps.auth enticator2) has stopped unexpectedly. Please try again.

How can i roll it back to how it was and had been for a long time? Why did it say it was compatible if it was not?

KDI-i360-v1.0
Android 2.3.6

**Comment by ThomasHabets** [comment]
Setting aside that this repo is about the opensource GA, not the one in play store, supporting a 7 year old Android version can't be expected on a volunteer basis.

Well-formed pull requests always accepted, though.

**Comment by ThomasHabets** [comment]
I'll pass along this report to the team maintaining the non-opensource version of GA, but can't promise anything.

**Comment by JackDinn** [comment]
Could i please have contact details of the team maintaining the non-opensource version of GA.

Thank you.

**Comment by RusGamer** [comment]
Maybe need download old version apk from other websites? Did you try it or its unsafe?

**Comment by ThomasHabets** [comment]
For attacks it's only as insecure as where you download it from.

But I also can't vouch for what will happen generally, nor am I an expert on this code.

As for contact details I can't give out more than what you see on [the play store](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en).

**Comment by JackDinn** [comment]
well thats exactly what i would like to do but i cant find any archives or previous .apk (even if i did trust them)

**Comment by ThomasHabets** [comment]
But also: what was your plan if your phone had been stolen or simply broke? Was all your bitcoins banking on this piece of hardware never breaking?

**Comment by RusGamer** [comment]
https://yadi.sk/d/dz8g2Fxz3Nz9ky old version of Google Auth.

**Comment by JackDinn** [comment]
I did actually keep the auth keys KZH********* in my last pass for every GA site that i used it on. Problem is without a device that will run GA i cant try and import them

**Comment by JackDinn** [comment]
ahh cheer RusGamer , i shall take a look. cheers.

**Comment by JackDinn** [comment]
so do we trust this archive ? is there a google pgp singing or even just md5 or sha1 etc of the file anywhere ?

**Comment by RusGamer** [comment]
its just old version of apk file. Dont know its help for you or not. I will try later

**Comment by JackDinn** [comment]
well should at least get me into accounts and disable 2FA , Thx.

**Comment by JackDinn** [comment]
I see that https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en is still saying that it IS compatible with my phone :-/ If they had just checked that it is not compatible with our version of android i would still have a working GA , I got this old phone exclusivity for GA and it has been fine for years, i would have been happy to just leave it at the previous version permanently.

**Comment by ThomasHabets** [comment]
@JackDinn yes, I mentioned that inconsistency in my message to the maintaining team.

**Comment by JackDinn** [comment]
well that .apk runs, iv added one of my keys but it will not connect to the time server so it wont sync the time/key. Interested to know how you get on with it RusGamer.

**Comment by JackDinn** [comment]
Ok, iv found that i needed to go back to version 4.60 to get everything to work. (the bar code scanner mainly) I still can not get it to sync the time but after manually adjusting the time i have managed to get it generating the correct codes.
https://www.apkmirror.com/apk/google-inc/authenticator/authenticator-4-60-release/google-authenticator-4-60-android-apk-download/

Hope i have not introduced any malicious code into my phone but thats the risk i suppose.

Thx to both of you for the help.

**Comment by RusGamer** [comment]
Did you replace you app when install old version. All old codes seems good?

**Comment by RusGamer** [comment]
Dont worry, Its original apk

**Comment by JackDinn** [comment]
looked good, i was installing several different versions on top of the currently installed versions and the keys were still there. 
Im my case though id already uninstalled and re-installed (as advised on reddit) and my keys were gone. 
So seems fine to over-wright the app but not to uninstall it and then re-install it.

**Comment by RusGamer** [comment]
YEEAH! I can do this ))

**Comment by JackDinn** [comment]
Good luck man :) , hope you get access to all your most important sites again ! luckily i had accounted for this eventuality and kept a copy of all the actual auth key numbers although not all sites actually gave them when setting up 2FA but iv got access my most important ones. 

Shall get another cheep phone and always keep two copies of GA and never update either again :-P

**Comment by ocdtrekkie** [comment]
Almost any site will give you a QR code when setting up which contains your secret. In addition to being super easy to scan with a phone, QR codes work great printed!

(I swear I've commented on GitHub by email reply before. Weird.)

**Comment by RusGamer** [comment]
if i will save reserve codes on my computer from my sites its will be stupid. Why i need google auth then))) maybe will beter save reserve codes just on paper xD.  
Now i can turn on my WIFI ? ))

**Comment by JackDinn** [comment]
indeed, mine were in my lastpass notes BUT encrypted with pgp
