### ISSUE TITLE
Recovering Two-factor Secrets After OS Upgrade

### ISSUE THREAD

**Issue by mhluska** [google/google-authenticator-android#71]
Around two years ago I installed an OS upgrade on my Android phone that caused my two-factor secrets to get lost (and subsequently lost access to a bitcoin wallet with ~75K in it). I was wondering if Google Authenticator backs up secrets to the cloud by any chance? Or does an OS upgrade permanently wipe those secrets?

**Comment by ThomasHabets** [comment]
OS upgrades in themselves should do nothing to app data. But if you meant you flashed your device, not OTA update, then the data is gone.

If you mean OTA update, file feedback / bug on Android itself, but no GA doesn't do backups.
