### ISSUE TITLE
Codes incorrectly generated on Blu Studio Energy runing android 4.4.2

### ISSUE THREAD

**Issue by dpippenger** [google/google-authenticator-android#8]
When running authenticator 2.49 on a Blu Studio Energy running 4.4.2 the generated codes are incorrect.

I also have a nexus 5 running 5.0.1, when inputting the same token seed to both phones the 4.4.2 device never generates the correct codes, while the 5.0.1 device using the same seed generates the proper codes.

I've also tried inputting the tokens using QR codes to eliminate the chance of user input error. I've confirmed the token codes are wrong for multiple sites including github, gmail, aws, several online games. 

The times are synced up and accurate on both phones, I've also attempted to use the app's "time correction for codes" feature in setup and it indicates no changes need to be made.

I've loaded the FreeOTP app from RedHat on the device and the token codes work properly in that app, which further supports it not being a time sync related issue on the device.

**Comment by ThomasHabets** [comment]
I think this is the same issue as #4, in which case it's fixed at least in this open source version.
