### ISSUE TITLE
Settings to change the code grouping from 2x 3digit to 3x 2digit

### ISSUE THREAD

**Issue by tg44** [google/google-authenticator-android#88]
Maybe its just me but whenever I open the app and read a code I read it in my head like `65 45 23` and not like `654 523`. It would be nice if I could switch the digit grouping.

**Comment by ThomasHabets** [comment]
FYI: The version in Google Play Store / Apple App store is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the app stores. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.

**Comment by tg44** [comment]
I'm sorry to hear that...
