### ISSUE TITLE
Bypass goole

### ISSUE THREAD

**Issue by locd2db1** [google/google-authenticator-android#93]

**Comment by MrPickles** [comment]
?

**Comment by ThomasHabets** [comment]
@MrPickles 
Yeah, this happens. Some bot accounts create random stuff just after creating an account. This account though seems to play the long game. I went through their activity and couldn't find anything implying it's legit, only operations maybe designed to build reputation.

Not that I know what a github account is useful for.

In any case what I do is report&block them.
